### ISSUE TITLE
llama3.2-1b-base gives 'RuntimeError: no tokenizer was found'

### ISSUE THREAD

**Issue by drtonyr** [pytorch/torchchat#1413]
### 🐛 Describe the bug

I'm following the basic 5+1 line instructions to get torchchat going with llama3.2-1b-base and it fails with `RuntimeError: no tokenizer was found at /home/tonyr/.torchchat/model-cache/meta-llama/Meta-Llama-3.2-1B/tokenizer.model`.  The 6 lines I'm using are from the README.md:
```text
git clone https://github.com/pytorch/torchchat.git
cd torchchat
python3 -m venv .venv
source .venv/bin/activate
./install/install_requirements.sh
python3 torchchat.py generate llama3.2-1b-base --prompt "write me a story about a boy and his bear"
```
I also have llama3.2-3b-base which exhibits the same behaviour.  Full logs are below, note I already have llama3.2-1b-base downloaded:
```text
(.venv) think1 tonyr: ls -lta /home/tonyr/.torchchat/model-cache/meta-llama/Meta-Llama-3.2-1B/
total 2424908
drwxrwxr-x 4 tonyr tonyr       4096 Dec  8 20:45 ..
drwxrwxr-x 4 tonyr tonyr       4096 Dec  8 20:40 .
drwxrwxr-x 2 tonyr tonyr       4096 Dec  8 20:40 original
-rw-rw-r-- 1 tonyr tonyr 2471677246 Dec  8 20:40 model.pth
-rw-rw-r-- 1 tonyr tonyr    9085657 Dec  8 20:38 tokenizer.json
-rw-rw-r-- 1 tonyr tonyr    2183982 Dec  8 20:38 tokenizer.model
-rw-rw-r-- 1 tonyr tonyr       1519 Dec  8 20:38 .gitattributes
-rw-rw-r-- 1 tonyr tonyr      50500 Dec  8 20:38 tokenizer_config.json
-rw-rw-r-- 1 tonyr tonyr        301 Dec  8 20:38 special_tokens_map.json
-rw-rw-r-- 1 tonyr tonyr        185 Dec  8 20:38 generation_config.json
-rw-rw-r-- 1 tonyr tonyr       7712 Dec  8 20:38 LICENSE.txt
-rw-rw-r-- 1 tonyr tonyr        843 Dec  8 20:38 config.json
-rw-rw-r-- 1 tonyr tonyr      41239 Dec  8 20:38 README.md
-rw-rw-r-- 1 tonyr tonyr       6021 Dec  8 20:38 USE_POLICY.md
drwxrwxr-x 3 tonyr tonyr       4096 Dec  8 20:38 .cache
```
Also note, there is a warning in the logs:
```text
+ python3 torchchat/utils/scripts/patch_triton.py
/home/tonyr/torchchat/torchchat/utils/scripts/patch_triton.py:20: SyntaxWarning: invalid escape sequence '\s'
  new_match = 'self.src = self.src[re.search(r"^def\s+\w+\s*\(", self.src, re.MULTILINE).start():]'
```
and here is the full log, the interesting bit is at the end.
```text
think1 tonyr: git clone https://github.com/pytorch/torchchat.git
Cloning into 'torchchat'...
remote: Enumerating objects: 14722, done.
remote: Counting objects: 100% (2820/2820), done.
remote: Compressing objects: 100% (598/598), done.
remote: Total 14722 (delta 2458), reused 2358 (delta 2211), pack-reused 11902 (from 1)
Receiving objects: 100% (14722/14722), 8.87 MiB | 24.88 MiB/s, done.
Resolving deltas: 100% (8755/8755), done.
think1 tonyr: cd torchchat
think1 tonyr: python3 -m venv .venv
think1 tonyr: source .venv/bin/activate
(.venv) think1 tonyr: ./install/install_requirements.sh
Using python executable: python3
Using pip executable: pip3
+ pip3 install -r install/requirements.txt --extra-index-url https://download.pytorch.org/whl/nightly/cu121
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cu121
Ignoring tomli: markers 'python_version < "3.11"' don't match your environment
Collecting huggingface_hub (from -r install/requirements.txt (line 4))
  Using cached huggingface_hub-0.26.5-py3-none-any.whl.metadata (13 kB)
Collecting gguf (from -r install/requirements.txt (line 7))
  Using cached gguf-0.10.0-py3-none-any.whl.metadata (3.5 kB)
Collecting tiktoken (from -r install/requirements.txt (line 10))
  Using cached https://download.pytorch.org/whl/nightly/tiktoken-0.8.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
[ deleted loads more Collecting .. Using cached ]]
Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Using cached lm_eval-0.4.2-py3-none-any.whl (1.4 MB)
Using cached huggingface_hub-0.26.5-py3-none-any.whl (447 kB)

Using cached smmap-5.0.1-py3-none-any.whl (24 kB)
Using cached yarl-1.18.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (336 kB)
Installing collected packages: zstd, word2number, sqlitedict, sentencepiece, pytz, mpmath, zstandard, xxhash, wheel, watchdog, urllib3, tzdata, typing-extensions, tqdm, tornado, toml, threadpoolctl, tenacity, tcolorpy, tabulate, sympy, sniffio, smmap, six, setuptools, safetensors, rpds-py, regex, pyyaml, pygments, pycryptodomex, pybind11, pyarrow, psutil, protobuf, propcache, portalocker, pillow, pathvalidate, packaging, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, ninja, networkx, narwhals, multidict, more-itertools, mdurl, MarkupSafe, lxml, joblib, jiter, itsdangerous, idna, h11, fsspec, frozenlist, filelock, distro, dill, colorama, cmake, click, charset-normalizer, chardet, certifi, cachetools, blinker, attrs, annotated-types, aiohappyeyeballs, absl-py, yarl, Werkzeug, triton, tqdm-multiprocess, snakeviz, scipy, sacrebleu, requests, referencing, python-dateutil, pydantic-core, nvidia-cusparse-cu12, nvidia-cudnn-cu12, numexpr, nltk, multiprocess, mbstrdecoder, markdown-it-py, jsonlines, Jinja2, httpcore, gitdb, gguf, blobfile, anyio, aiosignal, typepy, tiktoken, scikit-learn, rouge-score, rich, pydeck, pydantic, pandas, nvidia-cusolver-cu12, jsonschema-specifications, huggingface_hub, httpx, gitpython, flask, aiohttp, torch, tokenizers, openai, jsonschema, transformers, datasets, DataProperty, altair, accelerate, tabledata, streamlit, peft, evaluate, pytablewriter, lm_eval
Successfully installed DataProperty-1.0.1 Jinja2-3.1.4 MarkupSafe-3.0.2 Werkzeug-3.1.3 absl-py-2.1.0 accelerate-1.2.0 aiohappyeyeballs-2.4.4 aiohttp-3.11.10 aiosignal-1.3.1 altair-5.5.0 annotated-types-0.7.0 anyio-4.7.0 attrs-24.2.0 blinker-1.9.0 blobfile-3.0.0 cachetools-5.5.0 certifi-2024.8.30 chardet-5.2.0 charset-normalizer-3.4.0 click-8.1.7 cmake-3.31.1 colorama-0.4.6 datasets-3.1.0 dill-0.3.8 distro-1.9.0 evaluate-0.4.3 filelock-3.16.1 flask-3.1.0 frozenlist-1.5.0 fsspec-2024.9.0 gguf-0.10.0 gitdb-4.0.11 gitpython-3.1.43 h11-0.14.0 httpcore-1.0.7 httpx-0.28.1 huggingface_hub-0.26.5 idna-3.10 itsdangerous-2.2.0 jiter-0.8.2 joblib-1.4.2 jsonlines-4.0.0 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 lm_eval-0.4.2 lxml-5.3.0 markdown-it-py-3.0.0 mbstrdecoder-1.1.3 mdurl-0.1.2 more-itertools-10.5.0 mpmath-1.3.0 multidict-6.1.0 multiprocess-0.70.16 narwhals-1.16.0 networkx-3.4.2 ninja-1.11.1.2 nltk-3.9.1 numexpr-2.10.2 numpy-1.26.4 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 openai-1.57.1 packaging-24.2 pandas-2.2.3 pathvalidate-3.2.1 peft-0.14.0 pillow-11.0.0 portalocker-3.0.0 propcache-0.2.1 protobuf-5.29.1 psutil-6.1.0 pyarrow-18.1.0 pybind11-2.13.6 pycryptodomex-3.21.0 pydantic-2.10.3 pydantic-core-2.27.1 pydeck-0.9.1 pygments-2.18.0 pytablewriter-1.2.0 python-dateutil-2.9.0.post0 pytz-2024.2 pyyaml-6.0.2 referencing-0.35.1 regex-2024.11.6 requests-2.32.3 rich-13.9.4 rouge-score-0.1.2 rpds-py-0.22.3 sacrebleu-2.4.3 safetensors-0.4.5 scikit-learn-1.6.0 scipy-1.14.1 sentencepiece-0.2.0 setuptools-75.6.0 six-1.17.0 smmap-5.0.1 snakeviz-2.2.2 sniffio-1.3.1 sqlitedict-2.1.0 streamlit-1.40.2 sympy-1.13.1 tabledata-1.3.3 tabulate-0.9.0 tcolorpy-0.1.6 tenacity-9.0.0 threadpoolctl-3.5.0 tiktoken-0.8.0 tokenizers-0.21.0 toml-0.10.2 torch-2.5.1 tornado-6.4.2 tqdm-4.67.1 tqdm-multiprocess-0.0.11 transformers-4.47.0 triton-3.1.0 typepy-1.3.2 typing-extensions-4.12.2 tzdata-2024.2 urllib3-2.2.3 watchdog-6.0.0 wheel-0.45.1 word2number-1.1 xxhash-3.5.0 yarl-1.18.3 zstandard-0.23.0 zstd-1.5.5.1
+ pip3 uninstall -y triton
Found existing installation: triton 3.1.0
Uninstalling triton-3.1.0:
  Successfully uninstalled triton-3.1.0
+ pip3 install --extra-index-url https://download.pytorch.org/whl/nightly/cu121 torch==2.6.0.dev20241013 torchvision==0.20.0.dev20241013 torchtune==0.4.0.dev20241013
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cu121
Collecting torch==2.6.0.dev20241013
  Downloading https://download.pytorch.org/whl/nightly/cu121/torch-2.6.0.dev20241013%2Bcu121-cp312-cp312-linux_x86_64.whl (783.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 783.6/783.6 MB 1.3 MB/s eta 0:00:00
Collecting torchvision==0.20.0.dev20241013
  Downloading https://download.pytorch.org/whl/nightly/cu121/torchvision-0.20.0.dev20241013%2Bcu121-cp312-cp312-linux_x86_64.whl (7.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 10.2 MB/s eta 0:00:00
Collecting torchtune==0.4.0.dev20241013
  Downloading https://download.pytorch.org/whl/nightly/cu121/torchtune-0.4.0.dev20241013%2Bcu121-py3-none-any.whl (577 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 577.4/577.4 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: filelock in ./.venv/lib/python3.12/site-packages (from torch==2.6.0.dev20241013) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in ./.venv/lib/python3.12/site-packages (from torch==2.6.0.dev20241013) (4.12.2)
Requirement already satisfied: networkx in ./.venv/lib/python3.12/site-packages (from torch==2.6.0.dev20241013) (3.4.2)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.12/site-packages (from torch==2.6.0.dev20241013) (3.1.4)
Requirement already satisfied: fsspec in ./.venv/lib/python3.12/site-packages (from torch==2.6.0.dev20241013) (2024.9.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/cu121/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/cu121/nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/cu121/nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./.venv/lib/python3.12/site-packages (from torch==2.6.0.dev20241013) (9.1.0.70)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/cu121/nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/cu121/nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/cu121/nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/cu121/nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/cu121/nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in ./.venv/lib/python3.12/site-packages (from torch==2.6.0.dev20241013) (2.21.5)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/cu121/nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Collecting pytorch-triton==3.1.0+cf34004b8a (from torch==2.6.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/pytorch_triton-3.1.0%2Bcf34004b8a-cp312-cp312-linux_x86_64.whl (239.6 MB)
Requirement already satisfied: setuptools in ./.venv/lib/python3.12/site-packages (from torch==2.6.0.dev20241013) (75.6.0)
Requirement already satisfied: sympy==1.13.1 in ./.venv/lib/python3.12/site-packages (from torch==2.6.0.dev20241013) (1.13.1)
Requirement already satisfied: numpy in ./.venv/lib/python3.12/site-packages (from torchvision==0.20.0.dev20241013) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./.venv/lib/python3.12/site-packages (from torchvision==0.20.0.dev20241013) (11.0.0)
Requirement already satisfied: datasets in ./.venv/lib/python3.12/site-packages (from torchtune==0.4.0.dev20241013) (3.1.0)
Requirement already satisfied: huggingface-hub in ./.venv/lib/python3.12/site-packages (from torchtune==0.4.0.dev20241013) (0.26.5)
Requirement already satisfied: safetensors in ./.venv/lib/python3.12/site-packages (from torchtune==0.4.0.dev20241013) (0.4.5)
Requirement already satisfied: sentencepiece in ./.venv/lib/python3.12/site-packages (from torchtune==0.4.0.dev20241013) (0.2.0)
Requirement already satisfied: tiktoken in ./.venv/lib/python3.12/site-packages (from torchtune==0.4.0.dev20241013) (0.8.0)
Requirement already satisfied: blobfile>=2 in ./.venv/lib/python3.12/site-packages (from torchtune==0.4.0.dev20241013) (3.0.0)
Requirement already satisfied: tqdm in ./.venv/lib/python3.12/site-packages (from torchtune==0.4.0.dev20241013) (4.67.1)
Collecting omegaconf (from torchtune==0.4.0.dev20241013)
  Using cached https://download.pytorch.org/whl/nightly/omegaconf-2.3.0-py3-none-any.whl (79 kB)
Requirement already satisfied: psutil in ./.venv/lib/python3.12/site-packages (from torchtune==0.4.0.dev20241013) (6.1.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in ./.venv/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.6.0.dev20241013) (12.4.127)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.12/site-packages (from sympy==1.13.1->torch==2.6.0.dev20241013) (1.3.0)
Requirement already satisfied: pycryptodomex>=3.8 in ./.venv/lib/python3.12/site-packages (from blobfile>=2->torchtune==0.4.0.dev20241013) (3.21.0)
Requirement already satisfied: urllib3<3,>=1.25.3 in ./.venv/lib/python3.12/site-packages (from blobfile>=2->torchtune==0.4.0.dev20241013) (2.2.3)
Requirement already satisfied: lxml>=4.9 in ./.venv/lib/python3.12/site-packages (from blobfile>=2->torchtune==0.4.0.dev20241013) (5.3.0)
Requirement already satisfied: pyarrow>=15.0.0 in ./.venv/lib/python3.12/site-packages (from datasets->torchtune==0.4.0.dev20241013) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in ./.venv/lib/python3.12/site-packages (from datasets->torchtune==0.4.0.dev20241013) (0.3.8)
Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (from datasets->torchtune==0.4.0.dev20241013) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in ./.venv/lib/python3.12/site-packages (from datasets->torchtune==0.4.0.dev20241013) (2.32.3)
Requirement already satisfied: xxhash in ./.venv/lib/python3.12/site-packages (from datasets->torchtune==0.4.0.dev20241013) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in ./.venv/lib/python3.12/site-packages (from datasets->torchtune==0.4.0.dev20241013) (0.70.16)
Requirement already satisfied: aiohttp in ./.venv/lib/python3.12/site-packages (from datasets->torchtune==0.4.0.dev20241013) (3.11.10)
Requirement already satisfied: packaging in ./.venv/lib/python3.12/site-packages (from datasets->torchtune==0.4.0.dev20241013) (24.2)
Requirement already satisfied: pyyaml>=5.1 in ./.venv/lib/python3.12/site-packages (from datasets->torchtune==0.4.0.dev20241013) (6.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.12/site-packages (from jinja2->torch==2.6.0.dev20241013) (3.0.2)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf->torchtune==0.4.0.dev20241013)
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Requirement already satisfied: regex>=2022.1.18 in ./.venv/lib/python3.12/site-packages (from tiktoken->torchtune==0.4.0.dev20241013) (2024.11.6)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets->torchtune==0.4.0.dev20241013) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets->torchtune==0.4.0.dev20241013) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets->torchtune==0.4.0.dev20241013) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets->torchtune==0.4.0.dev20241013) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets->torchtune==0.4.0.dev20241013) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets->torchtune==0.4.0.dev20241013) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets->torchtune==0.4.0.dev20241013) (1.18.3)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets->torchtune==0.4.0.dev20241013) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets->torchtune==0.4.0.dev20241013) (3.10)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.12/site-packages (from requests>=2.32.2->datasets->torchtune==0.4.0.dev20241013) (2024.8.30)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas->datasets->torchtune==0.4.0.dev20241013) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas->datasets->torchtune==0.4.0.dev20241013) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.12/site-packages (from pandas->datasets->torchtune==0.4.0.dev20241013) (2024.2)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets->torchtune==0.4.0.dev20241013) (1.17.0)
Installing collected packages: antlr4-python3-runtime, pytorch-triton, omegaconf, nvidia-nvtx-cu12, nvidia-cusparse-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusolver-cu12, torch, torchvision, torchtune
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.4.127
    Uninstalling nvidia-nvtx-cu12-12.4.127:
      Successfully uninstalled nvidia-nvtx-cu12-12.4.127
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.3.1.170
    Uninstalling nvidia-cusparse-cu12-12.3.1.170:
      Successfully uninstalled nvidia-cusparse-cu12-12.3.1.170
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.5.147
    Uninstalling nvidia-curand-cu12-10.3.5.147:
      Successfully uninstalled nvidia-curand-cu12-10.3.5.147
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.1.3
    Uninstalling nvidia-cufft-cu12-11.2.1.3:
      Successfully uninstalled nvidia-cufft-cu12-11.2.1.3
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.4.127
    Uninstalling nvidia-cuda-runtime-cu12-12.4.127:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.4.127
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.4.127
    Uninstalling nvidia-cuda-nvrtc-cu12-12.4.127:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.4.127
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.4.127
    Uninstalling nvidia-cuda-cupti-cu12-12.4.127:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.4.127
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.4.5.8
    Uninstalling nvidia-cublas-cu12-12.4.5.8:
      Successfully uninstalled nvidia-cublas-cu12-12.4.5.8
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.1.9
    Uninstalling nvidia-cusolver-cu12-11.6.1.9:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.1.9
  Attempting uninstall: torch
    Found existing installation: torch 2.5.1
    Uninstalling torch-2.5.1:
      Successfully uninstalled torch-2.5.1
Successfully installed antlr4-python3-runtime-4.9.3 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nvtx-cu12-12.1.105 omegaconf-2.3.0 pytorch-triton-3.1.0+cf34004b8a torch-2.6.0.dev20241013+cu121 torchtune-0.4.0.dev20241013+cu121 torchvision-0.20.0.dev20241013+cu121
+ pip3 install torchao==0.5.0
Collecting torchao==0.5.0
  Using cached torchao-0.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Using cached torchao-0.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
Installing collected packages: torchao
Successfully installed torchao-0.5.0
+ python3 torchchat/utils/scripts/patch_triton.py
/home/tonyr/torchchat/torchchat/utils/scripts/patch_triton.py:20: SyntaxWarning: invalid escape sequence '\s'
  new_match = 'self.src = self.src[re.search(r"^def\s+\w+\s*\(", self.src, re.MULTILINE).start():]'
+ pip3 install evaluate==0.4.3 lm-eval==0.4.2 psutil==6.0.0
Requirement already satisfied: evaluate==0.4.3 in ./.venv/lib/python3.12/site-packages (0.4.3)
Requirement already satisfied: lm-eval==0.4.2 in ./.venv/lib/python3.12/site-packages (0.4.2)
Collecting psutil==6.0.0
  Using cached psutil-6.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: datasets>=2.0.0 in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (3.1.0)
Requirement already satisfied: numpy>=1.17 in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (1.26.4)
Requirement already satisfied: dill in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (0.3.8)
Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (4.67.1)
Requirement already satisfied: xxhash in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (3.5.0)
Requirement already satisfied: multiprocess in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in ./.venv/lib/python3.12/site-packages (from fsspec[http]>=2021.05.0->evaluate==0.4.3) (2024.9.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (0.26.5)
Requirement already satisfied: packaging in ./.venv/lib/python3.12/site-packages (from evaluate==0.4.3) (24.2)
Requirement already satisfied: accelerate>=0.21.0 in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (1.2.0)
Requirement already satisfied: jsonlines in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (4.0.0)
Requirement already satisfied: numexpr in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (2.10.2)
Requirement already satisfied: peft>=0.2.0 in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (0.14.0)
Requirement already satisfied: pybind11>=2.6.2 in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (2.13.6)
Requirement already satisfied: pytablewriter in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (1.2.0)
Requirement already satisfied: rouge-score>=0.0.4 in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (0.1.2)
Requirement already satisfied: sacrebleu>=1.5.0 in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (2.4.3)
Requirement already satisfied: scikit-learn>=0.24.1 in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (1.6.0)
Requirement already satisfied: sqlitedict in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (2.1.0)
Requirement already satisfied: torch>=1.8 in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (2.6.0.dev20241013+cu121)
Requirement already satisfied: tqdm-multiprocess in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (0.0.11)
Requirement already satisfied: transformers>=4.1 in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (4.47.0)
Requirement already satisfied: zstandard in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (0.23.0)
Requirement already satisfied: word2number in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (1.1)
Requirement already satisfied: more-itertools in ./.venv/lib/python3.12/site-packages (from lm-eval==0.4.2) (10.5.0)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.12/site-packages (from accelerate>=0.21.0->lm-eval==0.4.2) (6.0.2)
Requirement already satisfied: safetensors>=0.4.3 in ./.venv/lib/python3.12/site-packages (from accelerate>=0.21.0->lm-eval==0.4.2) (0.4.5)
Requirement already satisfied: filelock in ./.venv/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate==0.4.3) (3.16.1)
Requirement already satisfied: pyarrow>=15.0.0 in ./.venv/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate==0.4.3) (18.1.0)
Requirement already satisfied: aiohttp in ./.venv/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate==0.4.3) (3.11.10)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./.venv/lib/python3.12/site-packages (from huggingface-hub>=0.7.0->evaluate==0.4.3) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.12/site-packages (from requests>=2.19.0->evaluate==0.4.3) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.12/site-packages (from requests>=2.19.0->evaluate==0.4.3) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.12/site-packages (from requests>=2.19.0->evaluate==0.4.3) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.12/site-packages (from requests>=2.19.0->evaluate==0.4.3) (2024.8.30)
Requirement already satisfied: absl-py in ./.venv/lib/python3.12/site-packages (from rouge-score>=0.0.4->lm-eval==0.4.2) (2.1.0)
Requirement already satisfied: nltk in ./.venv/lib/python3.12/site-packages (from rouge-score>=0.0.4->lm-eval==0.4.2) (3.9.1)
Requirement already satisfied: six>=1.14.0 in ./.venv/lib/python3.12/site-packages (from rouge-score>=0.0.4->lm-eval==0.4.2) (1.17.0)
Requirement already satisfied: portalocker in ./.venv/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval==0.4.2) (3.0.0)
Requirement already satisfied: regex in ./.venv/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval==0.4.2) (2024.11.6)
Requirement already satisfied: tabulate>=0.8.9 in ./.venv/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval==0.4.2) (0.9.0)
Requirement already satisfied: colorama in ./.venv/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval==0.4.2) (0.4.6)
Requirement already satisfied: lxml in ./.venv/lib/python3.12/site-packages (from sacrebleu>=1.5.0->lm-eval==0.4.2) (5.3.0)
Requirement already satisfied: scipy>=1.6.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn>=0.24.1->lm-eval==0.4.2) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn>=0.24.1->lm-eval==0.4.2) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn>=0.24.1->lm-eval==0.4.2) (3.5.0)
Requirement already satisfied: networkx in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (3.4.2)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (12.1.105)
Requirement already satisfied: pytorch-triton==3.1.0+cf34004b8a in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (3.1.0+cf34004b8a)
Requirement already satisfied: setuptools in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (75.6.0)
Requirement already satisfied: sympy==1.13.1 in ./.venv/lib/python3.12/site-packages (from torch>=1.8->lm-eval==0.4.2) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in ./.venv/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.8->lm-eval==0.4.2) (12.4.127)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./.venv/lib/python3.12/site-packages (from sympy==1.13.1->torch>=1.8->lm-eval==0.4.2) (1.3.0)
Requirement already satisfied: tokenizers<0.22,>=0.21 in ./.venv/lib/python3.12/site-packages (from transformers>=4.1->lm-eval==0.4.2) (0.21.0)
Requirement already satisfied: attrs>=19.2.0 in ./.venv/lib/python3.12/site-packages (from jsonlines->lm-eval==0.4.2) (24.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas->evaluate==0.4.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas->evaluate==0.4.3) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.12/site-packages (from pandas->evaluate==0.4.3) (2024.2)
Requirement already satisfied: DataProperty<2,>=1.0.1 in ./.venv/lib/python3.12/site-packages (from pytablewriter->lm-eval==0.4.2) (1.0.1)
Requirement already satisfied: mbstrdecoder<2,>=1.0.0 in ./.venv/lib/python3.12/site-packages (from pytablewriter->lm-eval==0.4.2) (1.1.3)
Requirement already satisfied: pathvalidate<4,>=2.3.0 in ./.venv/lib/python3.12/site-packages (from pytablewriter->lm-eval==0.4.2) (3.2.1)
Requirement already satisfied: tabledata<2,>=1.3.1 in ./.venv/lib/python3.12/site-packages (from pytablewriter->lm-eval==0.4.2) (1.3.3)
Requirement already satisfied: tcolorpy<1,>=0.0.5 in ./.venv/lib/python3.12/site-packages (from pytablewriter->lm-eval==0.4.2) (0.1.6)
Requirement already satisfied: typepy<2,>=1.3.2 in ./.venv/lib/python3.12/site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->lm-eval==0.4.2) (1.3.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./.venv/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate==0.4.3) (1.18.3)
Requirement already satisfied: chardet<6,>=3.0.4 in ./.venv/lib/python3.12/site-packages (from mbstrdecoder<2,>=1.0.0->pytablewriter->lm-eval==0.4.2) (5.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.12/site-packages (from jinja2->torch>=1.8->lm-eval==0.4.2) (3.0.2)
Requirement already satisfied: click in ./.venv/lib/python3.12/site-packages (from nltk->rouge-score>=0.0.4->lm-eval==0.4.2) (8.1.7)
Using cached psutil-6.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (290 kB)
Installing collected packages: psutil
  Attempting uninstall: psutil
    Found existing installation: psutil 6.1.0
    Uninstalling psutil-6.1.0:
      Successfully uninstalled psutil-6.1.0
Successfully installed psutil-6.0.0
(failed reverse-i-search)`download': llama model ^Cwnload --source meta --model-id Llama3.2-3B 
(.venv) think1 tonyr: python3 torchchat.py list

Model                                        Aliases                                                    Downloaded 
-------------------------------------------- ---------------------------------------------------------- -----------
meta-llama/llama-2-7b-hf                     llama2-base, llama2-7b                                                
meta-llama/llama-2-7b-chat-hf                llama2, llama2-chat, llama2-7b-chat                                   
meta-llama/llama-2-13b-chat-hf               llama2-13b-chat                                                       
meta-llama/llama-2-70b-chat-hf               llama2-70b-chat                                                       
meta-llama/meta-llama-3-8b                   llama3-base                                                           
meta-llama/meta-llama-3-8b-instruct          llama3, llama3-chat, llama3-instruct                                  
meta-llama/meta-llama-3-70b-instruct         llama3-70b                                                            
meta-llama/meta-llama-3.1-8b                 llama3.1-base                                                         
meta-llama/meta-llama-3.1-8b-instruct        llama3.1, llama3.1-chat, llama3.1-instruct                            
meta-llama/meta-llama-3.1-70b-instruct       llama3.1-70b                                                          
meta-llama/meta-llama-3.1-8b-instruct-tune   llama3.1-tune, llama3.1-chat-tune, llama3.1-instruct-tune             
meta-llama/meta-llama-3.1-70b-instruct-tune  llama3.1-70b-tune                                                     
meta-llama/meta-llama-3.2-1b                 llama3.2-1b-base                                           Yes        
meta-llama/meta-llama-3.2-1b-instruct        llama3.2-1b, llama3.2-1b-chat, llama3.2-1b-instruct                   
meta-llama/llama-guard-3-1b                  llama3-1b-guard, llama3.2-1b-guard                                    
meta-llama/meta-llama-3.2-3b                 llama3.2-3b-base                                           Yes        
meta-llama/meta-llama-3.2-3b-instruct        llama3.2-3b, llama3.2-3b-chat, llama3.2-3b-instruct                   
meta-llama/llama-3.2-11b-vision              llama3.2-11B-base, Llama-3.2-11B-Vision-base                          
meta-llama/llama-3.2-11b-vision-instruct     llama3.2-11B, Llama-3.2-11B-Vision, Llama-3.2-mm                      
meta-llama/codellama-7b-python-hf            codellama, codellama-7b                                               
meta-llama/codellama-34b-python-hf           codellama-34b                                                         
mistralai/mistral-7b-v0.1                    mistral-7b-v01-base                                                   
mistralai/mistral-7b-instruct-v0.1           mistral-7b-v01-instruct                                               
mistralai/mistral-7b-instruct-v0.2           mistral, mistral-7b, mistral-7b-instruct                              
openlm-research/open_llama_7b                open-llama, open-llama-7b                                             
stories15m                                                                                                         
stories42m                                                                                                         
stories110m                                                                                                        

(.venv) think1 tonyr: python3 torchchat.py generate llama3.2-1b-base --prompt "write me a story about a boy and his bear"
NumExpr defaulting to 12 threads.
PyTorch version 2.6.0.dev20241013+cu121 available.
Using device=cuda NVIDIA GeForce RTX 4070 Ti
Loading model...
Time to load model: 0.90 seconds
-----------------------------------------------------------
Traceback (most recent call last):
  File "/home/tonyr/torchchat/torchchat.py", line 96, in <module>
    generate_main(args)
  File "/home/tonyr/torchchat/torchchat/generate.py", line 1235, in main
    gen = Generator(
          ^^^^^^^^^^
  File "/home/tonyr/torchchat/torchchat/generate.py", line 311, in __init__
    self.tokenizer_args.validate_model(self.model)
  File "/home/tonyr/torchchat/torchchat/cli/builder.py", line 264, in validate_model
    raise RuntimeError(f"no tokenizer was found at {self.tokenizer_path}")
RuntimeError: no tokenizer was found at /home/tonyr/.torchchat/model-cache/meta-llama/Meta-Llama-3.2-1B/tokenizer.model
```

### Versions

```text
(.venv) think1 tonyr: python3 ~/collect_env.py 
Collecting environment information...
PyTorch version: 2.6.0.dev20241013+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.1 LTS (x86_64)
GCC version: (Ubuntu 13.2.0-23ubuntu4) 13.2.0
Clang version: Could not collect
CMake version: version 3.31.1
Libc version: glibc-2.39

Python version: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] (64-bit runtime)
Python platform: Linux-6.8.0-49-generic-x86_64-with-glibc2.39
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4070 Ti
Nvidia driver version: 550.127.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               12
On-line CPU(s) list:                  0-11
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
CPU family:                           6
Model:                                45
Thread(s) per core:                   2
Core(s) per socket:                   6
Socket(s):                            1
Stepping:                             7
CPU(s) scaling MHz:                   78%
CPU max MHz:                          3800.0000
CPU min MHz:                          1200.0000
BogoMIPS:                             6403.76
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid xsaveopt dtherm ida arat pln pts vnmi md_clear flush_l1d
Virtualization:                       VT-x
L1d cache:                            192 KiB (6 instances)
L1i cache:                            192 KiB (6 instances)
L2 cache:                             1.5 MiB (6 instances)
L3 cache:                             12 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-11
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          KVM: Mitigation: VMX disabled
Vulnerability L1tf:                   Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:                    Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:               Mitigation; PTI
Vulnerability Mmio stale data:        Unknown: No mitigations
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP conditional; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pytorch-triton==3.1.0+cf34004b8a
[pip3] torch==2.6.0.dev20241013+cu121
[pip3] torchao==0.5.0
[pip3] torchtune==0.4.0.dev20241013+cu121
[pip3] torchvision==0.20.0.dev20241013+cu121
[conda] Could not collect
(.venv) think1 tonyr: 
```

**Comment by Jack-Khuu** [comment]
Hmm looks like the migration https://github.com/pytorch/torchchat/commit/fff956c5c3a68025025c5d906af80eb44e960ce4 messed something up

Taking a look

**Comment by Jack-Khuu** [comment]
https://github.com/pytorch/torchchat/pull/1414

**Comment by Jack-Khuu** [comment]
Should work now, feel free to reopen and let us know if it doesn't

**Comment by drtonyr** [comment]
Fantastic, it now works for me - thanks so much for the quick fix.
